//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;

namespace DataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Training = new HashSet<Training>();
        }
        [Key]
        public int ClientId { get; set; }
        public string ClientFIO { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public long ClientCash { get; set; }
    
        public virtual ICollection<Training> Training { get; set; }
    }
}
