//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public Place()
        {
            this.Training = new HashSet<Training>();
        }
    
        public int PlaceId { get; set; }
        public string PlaceName { get; set; }
        public int Capacity { get; set; }
    
        public virtual ICollection<Training> Training { get; set; }
    }
}
