//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public Sport()
        {
            this.Trainer = new HashSet<Trainer>();
        }
    
        public int SportId { get; set; }
        public string SportName { get; set; }
        public string SportsType { get; set; }
    
        public virtual ICollection<Trainer> Trainer { get; set; }
    }
}
