//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingId { get; set; }
        public int TrainingType { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public int Trainer { get; set; }
        public int Place { get; set; }
        public int Client { get; set; }
        public int Cost { get; set; }

        public virtual Client Client1 { get; set; }
        public virtual Place Place1 { get; set; }
        public virtual Trainer Trainer1 { get; set; }
    }
}
