//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        public Trainer()
        {
            this.Training = new HashSet<Training>();
        }
    
        public int TrainerId { get; set; }
        public string TrainerFIO { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Achievements { get; set; }
        public int SportsType { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual ICollection<Training> Training { get; set; }
    }
}
