//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int TrainingId { get; set; }
        public int TrainingType { get; set; }
        public System.DateTime TrainingDate { get; set; }
        public int Trainer { get; set; }
        public int Place { get; set; }
        public int Client { get; set; }
        public int Cost { get; set; }
        public int CountOfFreePlaces { get; set; }
    
        public virtual Client Client1 { get; set; }
        public virtual Place Place1 { get; set; }
        public virtual Trainer Trainer1 { get; set; }
    }
}
